## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('udp-echo', ['csma', 'internet', 'applications'])
    obj.source = 'udp-echo.cc'
    obj = bld.create_ns3_program('request-response', ['point-to-point', 'internet', 'applications'])
    obj.source = 'request-response.cc'
    obj = bld.create_ns3_program('udp-echo1', ['csma', 'internet', 'applications'])
    obj.source = 'udp-echo1.cc'
